# Generated by Django 3.1.8 on 2021-05-06 07:57

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20210504_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(verbose_name=datetime.datetime(2021, 5, 6, 13, 27, 43, 399013))),
                ('body', ckeditor.fields.RichTextField()),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
